# Generated by Django 5.0.4 on 2025-09-18 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hsn_code', models.CharField(blank=True, max_length=20, null=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='products/')),
                ('name', models.CharField(max_length=255)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('mrp', models.FloatField()),
                ('purchase_price', models.FloatField()),
                ('purchase_discount', models.FloatField(default=0)),
                ('purchase_tax', models.FloatField(default=0)),
                ('purchase_price_100', models.FloatField(blank=True, null=True)),
                ('purchase_tax_100', models.FloatField(default=0)),
                ('sale_price', models.FloatField()),
                ('sale_discount', models.FloatField(default=0)),
                ('sale_tax', models.FloatField(default=0)),
                ('sale_price_100', models.FloatField(blank=True, null=True)),
                ('sale_tax_100', models.FloatField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
