# Generated by Django 5.0.4 on 2025-09-23 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricemanagement_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='pcs_size',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
