# Generated by Django 5.0.4 on 2025-09-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricemanagement_app', '0002_product_pcs_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='final_purchase_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='final_sale_price',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_discount_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_tax_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_discount_price',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_tax_price',
            field=models.FloatField(default=0),
        ),
    ]
