# Generated by Django 5.0.4 on 2025-10-07 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricemanagement_app', '0003_product_final_purchase_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='purchase_discount_100',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_discount_price_100',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='purchase_tax_price_100',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_discount_100',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_discount_price_100',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='sale_tax_price_100',
            field=models.FloatField(default=0),
        ),
    ]
