# Generated by Django 5.0.4 on 2025-10-08 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pricemanagement_app', '0004_product_purchase_discount_100_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Product',
        ),
    ]
