# Generated by Django 5.0.4 on 2025-10-08 10:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pricemanagement_app', '0005_delete_product'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(upload_to='products/')),
                ('name', models.CharField(max_length=200)),
                ('size', models.CharField(blank=True, max_length=50, null=True)),
                ('code', models.CharField(max_length=50, unique=True)),
                ('hsn', models.CharField(blank=True, max_length=50, null=True)),
                ('mrp', models.FloatField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='ProductPrice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(choices=[('cash', 'Cash'), ('bill', 'Bill'), ('sale_cash', 'Sale Cash'), ('sale_bill', 'Sale Bill'), ('frd_cash', 'Frd Cash'), ('frd_bill', 'Frd Bill')], max_length=20)),
                ('price', models.FloatField(default=0)),
                ('discount', models.FloatField(default=0)),
                ('discount_price', models.FloatField(default=0)),
                ('tax', models.FloatField(default=0)),
                ('tax_price', models.FloatField(default=0)),
                ('box', models.FloatField(default=0)),
                ('box_discount', models.FloatField(default=0)),
                ('box_discount_price', models.FloatField(default=0)),
                ('box_tax', models.FloatField(default=0)),
                ('box_tax_price', models.FloatField(default=0)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prices', to='pricemanagement_app.product')),
            ],
        ),
        migrations.CreateModel(
            name='Dealer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dlr_name', models.CharField(max_length=100)),
                ('slol', models.CharField(blank=True, max_length=100, null=True)),
                ('purchase_date', models.DateField(blank=True, null=True)),
                ('purchase_price', models.FloatField(default=0)),
                ('purchase_discount', models.FloatField(default=0)),
                ('purchase_discount_price', models.FloatField(default=0)),
                ('purchase_tax', models.FloatField(default=0)),
                ('purchase_tax_price', models.FloatField(default=0)),
                ('purchase_box', models.FloatField(default=0)),
                ('purchase_box_discount', models.FloatField(default=0)),
                ('purchase_box_discount_price', models.FloatField(default=0)),
                ('purchase_box_tax', models.FloatField(default=0)),
                ('purchase_box_tax_price', models.FloatField(default=0)),
                ('product_price', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='dealers', to='pricemanagement_app.productprice')),
            ],
        ),
    ]
