# Generated by Django 5.0.4 on 2025-10-08 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pricemanagement_app', '0007_alter_dealer_dlr_name_alter_product_mrp_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='code',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
