# Generated by Django 5.2.6 on 2025-10-13 17:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("pricemanagement_app", "0009_remove_product_code_remove_product_hsn_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="productprice",
            name="product",
        ),
        migrations.AddField(
            model_name="productprice",
            name="product_size",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="pricemanagement_app.productsize",
            ),
        ),
    ]
