# Generated by Django 5.0.4 on 2025-09-03 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0004_order_is_percentage_order_order_discount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='is_percentage',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cart',
            name='item_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
