# Generated by Django 5.0.4 on 2025-09-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0009_alter_inventory_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='pending_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='total_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='total_gst',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='order',
            name='total_item_discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
        migrations.AddField(
            model_name='sale',
            name='paid_amount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=20),
        ),
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('cod', 'cod'), ('online', 'online'), ('card', 'card')], max_length=200, null=True),
        ),
    ]
