# Generated by Django 5.0.4 on 2025-09-11 07:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0010_customer_pending_amount_order_subtotal_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='pay_type',
            field=models.CharField(blank=True, choices=[('cash', 'cash'), ('online', 'online'), ('card', 'card')], max_length=200, null=True),
        ),
    ]
