# Generated by Django 5.0.4 on 2025-09-18 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory_app', '0011_alter_order_pay_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='advance_payment',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
        ),
    ]
