# Generated by Django 5.0.4 on 2025-11-09 11:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory_app", "0016_alter_order_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="return_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total amount returned to customer",
                max_digits=12,
            ),
        ),
    ]
